import "./globals.css";
import { Varela_Round } from "next/font/google";

const font = Varela_Round({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="w-screen h-screen flex items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
